using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace app.Services.Titan
{
    #region Titan Status
    public class Err
    {
        public string e { get; set; }

    }
    public class TitanResponse
    {
        public string model { get; set; }
        public string name { get; set; }
        public string serial { get; set; }
        public int time { get; set; }
        public int chkId { get; set; }
        public int JrnTime { get; set; }
        public int currZ { get; set; }
        public int IsWrk { get; set; }
        public int Fiscalization { get; set; }
        public int FskMode { get; set; }
        public IList<Err> err { get; set; }
    }
    #endregion

    #region Titan Error
    public class TitanErrorResponse
    {
        public Error err { get; set; }
    }

    public class Error
    {
        public string e { get; set; }
        public int line { get; set; }
        public string err { get; set; }
    }
    public class TitanDictionaryError
    {
        public Ru Ru { get; set; }
    }
    public class Ru
    {
        public Dictionary<string, string> Err { get; set; }

    }
    #endregion
}


// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CodeBeautify;
//
//    var welcome6 = Welcome6.FromJson(jsonString);

//namespace CodeBeautify
//{
//    using System;
//    using System.Collections.Generic;

//    using System.Globalization;
//    using Newtonsoft.Json;
//    using Newtonsoft.Json.Converters;

//    public partial class Welcome6
//    {
//        [JsonProperty("def")]
//        public string Def { get; set; }

//        [JsonProperty("regex")]
//        public Regex Regex { get; set; }

//        [JsonProperty("en")]
//        public En En { get; set; }

//        [JsonProperty("ru")]
//        public Ru Ru { get; set; }
//    }

//    public partial class En
//    {
//        [JsonProperty("err")]
//        public Dictionary<string, string> Err { get; set; }

//        [JsonProperty("tbl")]
//        public EnTbl Tbl { get; set; }
//    }

//    public partial class EnTbl
//    {
//        [JsonProperty("Time")]
//        public Time Time { get; set; }

//        [JsonProperty("Hdr")]
//        public PayClass Hdr { get; set; }

//        [JsonProperty("Ftr")]
//        public PayClass Ftr { get; set; }

//        [JsonProperty("Oper")]
//        public Dep Oper { get; set; }

//        [JsonProperty("Dep")]
//        public Dep Dep { get; set; }

//        [JsonProperty("Grp")]
//        public Dep Grp { get; set; }

//        [JsonProperty("Dsc")]
//        public Dsc Dsc { get; set; }

//        [JsonProperty("Pay")]
//        public PayClass Pay { get; set; }

//        [JsonProperty("Adm")]
//        public Adm Adm { get; set; }

//        [JsonProperty("Flg")]
//        public PurpleFlg Flg { get; set; }

//        [JsonProperty("Tax")]
//        public Tax Tax { get; set; }

//        [JsonProperty("Fsk")]
//        public Fsk Fsk { get; set; }

//        [JsonProperty("PLU")]
//        public PurplePlu Plu { get; set; }

//        [JsonProperty("Dir")]
//        public Dir Dir { get; set; }

//        [JsonProperty("Host")]
//        public PurpleHost Host { get; set; }

//        [JsonProperty("TCP")]
//        public Tcp Tcp { get; set; }
//    }

//    public partial class Adm
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("ParPrg")]
//        public CurTim ParPrg { get; set; }

//        [JsonProperty("OtcPrg")]
//        public CurTim OtcPrg { get; set; }

//        [JsonProperty("NumOpr")]
//        public CurTim NumOpr { get; set; }

//        [JsonProperty("CurTim")]
//        public CurTim CurTim { get; set; }

//        [JsonProperty("PrContr")]
//        public CurTim PrContr { get; set; }

//        [JsonProperty("PrEqual")]
//        public CurTim PrEqual { get; set; }

//        [JsonProperty("ScrCntr")]
//        public CurTim ScrCntr { get; set; }
//    }

//    public partial class CurTim
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }
//    }

//    public partial class Dep
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("id")]
//        public CurTim Id { get; set; }

//        [JsonProperty("Name")]
//        public CurTim Name { get; set; }

//        [JsonProperty("Pswd", NullValueHandling = NullValueHandling.Ignore)]
//        public CurTim Pswd { get; set; }
//    }

//    public partial class Dir
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("Klav")]
//        public CurTim Klav { get; set; }

//        [JsonProperty("Code")]
//        public CurTim Code { get; set; }
//    }

//    public partial class Dsc
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("NcDsb")]
//        public CurTim NcDsb { get; set; }

//        [JsonProperty("Nac")]
//        public CurTim Nac { get; set; }

//        [JsonProperty("SkDsb")]
//        public CurTim SkDsb { get; set; }

//        [JsonProperty("Skd")]
//        public CurTim Skd { get; set; }

//        [JsonProperty("PNDsb")]
//        public CurTim PnDsb { get; set; }

//        [JsonProperty("PNac")]
//        public CurTim PNac { get; set; }

//        [JsonProperty("PSDsb")]
//        public CurTim PsDsb { get; set; }

//        [JsonProperty("PSkd")]
//        public CurTim PSkd { get; set; }
//    }

//    public partial class PurpleFlg
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("PrintOff")]
//        public CurTim PrintOff { get; set; }

//        [JsonProperty("Flg1")]
//        public CurTim Flg1 { get; set; }

//        [JsonProperty("Feed")]
//        public CurTim Feed { get; set; }

//        [JsonProperty("Flg3")]
//        public CurTim Flg3 { get; set; }
//    }

//    public partial class Fsk
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("ModelName")]
//        public CurTim ModelName { get; set; }

//        [JsonProperty("NumSKNO")]
//        public CurTim NumSkno { get; set; }

//        [JsonProperty("RegNum")]
//        public CurTim RegNum { get; set; }

//        [JsonProperty("UNP")]
//        public CurTim Unp { get; set; }

//        [JsonProperty("NumPnt")]
//        public CurTim NumPnt { get; set; }

//        [JsonProperty("NumChk")]
//        public CurTim NumChk { get; set; }
//    }

//    public partial class PayClass
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("id")]
//        public CurTim Id { get; set; }

//        [JsonProperty("Param", NullValueHandling = NullValueHandling.Ignore)]
//        public Param Param { get; set; }

//        [JsonProperty("Line", NullValueHandling = NullValueHandling.Ignore)]
//        public CurTim Line { get; set; }

//        [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
//        public CurTim Name { get; set; }

//        [JsonProperty("Pswd", NullValueHandling = NullValueHandling.Ignore)]
//        public CurTim Pswd { get; set; }
//    }

//    public partial class Param
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("help", NullValueHandling = NullValueHandling.Ignore)]
//        public string[] Help { get; set; }
//    }

//    public partial class PurpleHost
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("Name")]
//        public Name Name { get; set; }
//    }

//    public partial class Name
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("help")]
//        public string Help { get; set; }
//    }

//    public partial class PurplePlu
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("Code")]
//        public CurTim Code { get; set; }

//        [JsonProperty("Name")]
//        public CurTim Name { get; set; }

//        [JsonProperty("Price")]
//        public CurTim Price { get; set; }

//        [JsonProperty("Dep")]
//        public CurTim Dep { get; set; }

//        [JsonProperty("Grp")]
//        public CurTim Grp { get; set; }

//        [JsonProperty("Tax")]
//        public CurTim Tax { get; set; }

//        [JsonProperty("Qty")]
//        public CurTim Qty { get; set; }

//        [JsonProperty("Flg")]
//        public CurTim Flg { get; set; }
//    }

//    public partial class Tax
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("id")]
//        public CurTim Id { get; set; }

//        [JsonProperty("Prc")]
//        public CurTim Prc { get; set; }
//    }

//    public partial class Tcp
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("id")]
//        public CurTim Id { get; set; }

//        [JsonProperty("Addr")]
//        public CurTim Addr { get; set; }

//        [JsonProperty("Gate")]
//        public CurTim Gate { get; set; }

//        [JsonProperty("Mask")]
//        public CurTim Mask { get; set; }

//        [JsonProperty("DNS")]
//        public CurTim Dns { get; set; }

//        [JsonProperty("MAC")]
//        public CurTim Mac { get; set; }

//        [JsonProperty("AdptFlg")]
//        public Param AdptFlg { get; set; }

//        [JsonProperty("SysLog", NullValueHandling = NullValueHandling.Ignore)]
//        public SysLog SysLog { get; set; }
//    }

//    public partial class SysLog
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("Addr")]
//        public Name Addr { get; set; }

//        [JsonProperty("Port")]
//        public Name Port { get; set; }

//        [JsonProperty("Priority")]
//        public Name Priority { get; set; }

//        [JsonProperty("Trans", NullValueHandling = NullValueHandling.Ignore)]
//        public Name Trans { get; set; }
//    }

//    public partial class Time
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("Time")]
//        public CurTim TimeTime { get; set; }

//        [JsonProperty("Date")]
//        public CurTim Date { get; set; }
//    }

//    public partial class Regex
//    {
//        [JsonProperty("v_IP4")]
//        public string VIp4 { get; set; }

//        [JsonProperty("v_MAC")]
//        public string VMac { get; set; }

//        [JsonProperty("v_BaudN")]
//        public string VBaudN { get; set; }

//        [JsonProperty("v_BaudC")]
//        public string VBaudC { get; set; }

//        [JsonProperty("v_Cen_9x8")]
//        public string VCen9X8 { get; set; }

//        [JsonProperty("v_Cen_9x9")]
//        public string VCen9X9 { get; set; }

//        [JsonProperty("v_Num_0_1")]
//        public string VNum0_1 { get; set; }

//        [JsonProperty("v_Num_0_2")]
//        public string VNum0_2 { get; set; }

//        [JsonProperty("v_Num_0_4")]
//        public string VNum0_4 { get; set; }

//        [JsonProperty("v_Num_0_8")]
//        public string VNum0_8 { get; set; }

//        [JsonProperty("v_Num_0_15")]
//        public string VNum0_15 { get; set; }

//        [JsonProperty("v_Num_0_16")]
//        public string VNum0_16 { get; set; }

//        [JsonProperty("v_Num_0_20")]
//        public string VNum0_20 { get; set; }

//        [JsonProperty("v_Num_0_255")]
//        public string VNum0_255 { get; set; }

//        [JsonProperty("v_Num_10_40")]
//        public string VNum10_40 { get; set; }

//        [JsonProperty("v_Num_20_60")]
//        public string VNum20_60 { get; set; }

//        [JsonProperty("v_Num_9x18")]
//        public string VNum9X18 { get; set; }

//        [JsonProperty("v_Prc_99_99")]
//        public string VPrc99_99 { get; set; }

//        [JsonProperty("v_Pswd")]
//        public string VPswd { get; set; }

//        [JsonProperty("v_Qty_999999_999")]
//        public string VQty999999_999 { get; set; }

//        [JsonProperty("v_Str9")]
//        public string VStr9 { get; set; }

//        [JsonProperty("v_Str12")]
//        public string VStr12 { get; set; }

//        [JsonProperty("v_Str20")]
//        public string VStr20 { get; set; }

//        [JsonProperty("v_Str29")]
//        public string VStr29 { get; set; }

//        [JsonProperty("v_Str32")]
//        public string VStr32 { get; set; }

//        [JsonProperty("v_Dummy")]
//        public string VDummy { get; set; }
//    }

//    public partial class Ru
//    {
//        [JsonProperty("err")]
//        public Dictionary<string, string> Err { get; set; }

//        [JsonProperty("tbl")]
//        public RuTbl Tbl { get; set; }
//    }

//    public partial class RuTbl
//    {
//        [JsonProperty("Time")]
//        public Time Time { get; set; }

//        [JsonProperty("Com")]
//        public Com Com { get; set; }

//        [JsonProperty("Hdr")]
//        public PurpleFtr Hdr { get; set; }

//        [JsonProperty("Ftr")]
//        public PurpleFtr Ftr { get; set; }

//        [JsonProperty("Oper")]
//        public PayClass Oper { get; set; }

//        [JsonProperty("Dep")]
//        public PayClass Dep { get; set; }

//        [JsonProperty("Grp")]
//        public PayClass Grp { get; set; }

//        [JsonProperty("Dsc")]
//        public Dsc Dsc { get; set; }

//        [JsonProperty("Pay")]
//        public PayClass Pay { get; set; }

//        [JsonProperty("Adm")]
//        public Adm Adm { get; set; }

//        [JsonProperty("Flg")]
//        public FluffyFlg Flg { get; set; }

//        [JsonProperty("Tax")]
//        public Tax Tax { get; set; }

//        [JsonProperty("Fsk")]
//        public Fsk Fsk { get; set; }

//        [JsonProperty("PLU")]
//        public FluffyPlu Plu { get; set; }

//        [JsonProperty("Dir")]
//        public Dir Dir { get; set; }

//        [JsonProperty("TCP")]
//        public Tcp Tcp { get; set; }

//        [JsonProperty("Host")]
//        public FluffyHost Host { get; set; }

//        [JsonProperty("WiFi")]
//        public WiFi WiFi { get; set; }

//        [JsonProperty("SysLog")]
//        public SysLog SysLog { get; set; }
//    }

//    public partial class Com
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("id")]
//        public CurTim Id { get; set; }

//        [JsonProperty("Device")]
//        public Param Device { get; set; }

//        [JsonProperty("Baud")]
//        public CurTim Baud { get; set; }
//    }

//    public partial class FluffyFlg
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("NFoot")]
//        public CurTim NFoot { get; set; }

//        [JsonProperty("PrintOff")]
//        public Param PrintOff { get; set; }

//        [JsonProperty("Flg1")]
//        public Param Flg1 { get; set; }

//        [JsonProperty("Feed")]
//        public CurTim Feed { get; set; }

//        [JsonProperty("Flg3")]
//        public Param Flg3 { get; set; }
//    }

//    public partial class PurpleFtr
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("id")]
//        public CurTim Id { get; set; }

//        [JsonProperty("Param")]
//        public Param Param { get; set; }

//        [JsonProperty("Line")]
//        public CurTim Line { get; set; }
//    }

//    public partial class FluffyHost
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("Name")]
//        public CurTim Name { get; set; }
//    }

//    public partial class FluffyPlu
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("Code")]
//        public CurTim Code { get; set; }

//        [JsonProperty("Name")]
//        public Name Name { get; set; }

//        [JsonProperty("Price")]
//        public CurTim Price { get; set; }

//        [JsonProperty("Dep")]
//        public CurTim Dep { get; set; }

//        [JsonProperty("Grp")]
//        public CurTim Grp { get; set; }

//        [JsonProperty("Tax")]
//        public Name Tax { get; set; }

//        [JsonProperty("Qty")]
//        public CurTim Qty { get; set; }

//        [JsonProperty("Flg")]
//        public Param Flg { get; set; }
//    }

//    public partial class WiFi
//    {
//        [JsonProperty("label")]
//        public string Label { get; set; }

//        [JsonProperty("Enable")]
//        public CurTim Enable { get; set; }

//        [JsonProperty("SSID")]
//        public CurTim Ssid { get; set; }

//        [JsonProperty("Psw")]
//        public CurTim Psw { get; set; }
//    }

//    public partial class Welcome6
//    {
//        public static Welcome6 FromJson(string json) => JsonConvert.DeserializeObject<Welcome6>(json, CodeBeautify.Converter.Settings);
//    }

//    public static class Serialize
//    {
//        public static string ToJson(this Welcome6 self) => JsonConvert.SerializeObject(self, CodeBeautify.Converter.Settings);
//    }

//    internal static class Converter
//    {
//        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
//        {
//            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
//            DateParseHandling = DateParseHandling.None,
//            Converters =
//            {
//                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
//            },
//        };
//    }
//}
